#spring:
#  multiple:
#    datasource:
#      account:
#        url: jdbc:mysql://127.0.0.1:3306/account?useSSL=false&characterEncoding=utf-8&autoReconnect=true&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&useUnicode=true&autoReconnect=true&failOverReadOnly=false&useAffectedRows=true
#        driverClassName: com.mysql.cj.jdbc.Driver
#        username: root
#        password: root
#        hikari:
#          poolName: HikariCP-account
#          minimumIdle: 20
#          idleTimeout: 600000
#          maximumPoolSize: 100
#          autoCommit: true
#          maxLifetime: 1800000
#          connectionTimeout: 30000
#          connectionTestQuery: SELECT 1
#        mybatis:
#          typeAliasesPackage: io.github.zhoujunlin94.server.common.repository.db.entity
#          mapperLocation: classpath:mybatis/*.xml
#          basePackages: io.github.zhoujunlin94.server.common.repository.db.mapper
#          interceptors:
#            - clazz: com.github.pagehelper.PageInterceptor
#              properties:
#                helperDialect: mysql
#                reasonable: true
#                supportMethodsArguments: true