server:
  port: 80

spring:
  profiles:
    active: dev
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          # 让gateway发现nacos中的微服务
          enabled: true
      routes:
        - id: route_common
          # 满足下方断言的路由负载均衡到server-common微服务
          uri: lb://server-common
          predicates:
            - Path=/shop-common/**
          filters:
            # 局部过滤器（命名规范：StripPrefixGatewayFilterFactory）：截去路径中的第一个前缀   这里是shop-common
            - StripPrefix=1
        - id: route_account
          uri: lb://server-account
          predicates:
            - Path=/shop-account/**
          filters:
            - StripPrefix=1
        - id: route_order
          uri: lb://server-order
          predicates:
            - Path=/shop-order/**
          filters:
            - StripPrefix=1
        - id: route_product
          uri: lb://server-product
          predicates:
            - Path=/shop-product/**
          filters:
            - StripPrefix=1
        - id: route_sso
          uri: lb://server-sso
          predicates:
            - Path=/shop-sso/**
          filters:
            - StripPrefix=1
            # 自定义过滤器  用户打印接口执行时间
            # - Time=true