server:
  port: 80

spring:
  profiles:
    include: nacos, sentinel
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          #          让gateway发现nacos中的微服务
          enabled: true
      routes:
        - id: product_route
          # 满足下方断言的路由负载均衡到server-product微服务
          uri: lb://server-product
          predicates:
            - Path=/shop-product/**
          filters:
            # 局部过滤器（命名规范：StripPrefixGatewayFilterFactory）：截去路径中的第一个前缀   这里是shop-product
            - StripPrefix=1
        - id: order_route
          uri: lb://server-order
          predicates:
            - Path=/shop-order/**
          filters:
            - StripPrefix=1
            # 自定义过滤器  用户打印接口执行时间
            - Time=true