server:
  port: 80

spring:
  profiles:
    include: nacos
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          #          让gateway发现nacos中的微服务
          enabled: true