spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: d98ef8a5-ada3-40f6-a9fa-ee576fc5f88f
    sentinel:
      transport:
        dashboard: localhost:8858
      web-context-unify: false
