# 默认路由规则  使用微服务名

### 商品服务
GET http://127.0.0.1/server-product/internal/api/v1/product/findById?productId=1


###  自定义路由规则
### 商品服务
GET http://127.0.0.1/shop-product/internal/api/v1/product/findById?productId=1


