#####
# 1. 启动docker
# 2. 启动mysql并准备数据
# 3. 执行sql: nacos-mysql.sql  user.sql  account.sql  product.sql  order.sql
# 3. 启动rocketmq, redis, nacos, sentinel, seata
# 2. 准备好nacos配置（新建dev命名空间） 导入infrastructure.yaml和server-product.yaml
# 3. 启动server-account、server-product、server-order
# 4. 启动server-sso、api-gateway
#####

### 1. 注册用户
POST http://127.0.0.1/shop-sso/api/v1/user/register
Content-Type: application/json

{
  "nickname": "测试seata",
  "phone": "18566666666",
  "pwd": "ceshi"
}

### 2. 登录获取token
POST http://127.0.0.1/shop-sso/api/v1/user/login
Content-Type: application/json

{
  "nickname": "测试seata",
  "phone": "18566666666",
  "pwd": "ceshi"
}

### 3. 创建订单
### 3.1 事务正常提交
POST http://127.0.0.1/shop-order/api/v1/order/createOrder
Content-Type: application/x-www-form-urlencoded
Authentication: ebccb25e-dee8-4e69-875c-dfb71c1a3d55

productId=1


### 3.2 事务回滚(扣库存失败)
POST http://127.0.0.1/shop-order/api/v1/order/createOrder
Content-Type: application/x-www-form-urlencoded
Authentication: ebccb25e-dee8-4e69-875c-dfb71c1a3d55

productId=1&number=200000


### 3.2 事务回滚(扣款失败)
POST http://127.0.0.1/shop-order/api/v1/order/createOrder
Content-Type: application/x-www-form-urlencoded
Authentication: ebccb25e-dee8-4e69-875c-dfb71c1a3d55

productId=1&number=2000



### 4. 创建订单 (不经过网关)
### 3.1 事务正常提交
POST http://127.0.0.1:8190/api/v1/order/createOrder
Content-Type: application/x-www-form-urlencoded
X-GATEWAY-UID: 2

productId=1


### 3.2 事务回滚(扣库存失败)
POST http://127.0.0.1:8190/api/v1/order/createOrder
Content-Type: application/x-www-form-urlencoded
X-GATEWAY-UID: 2

productId=1&number=200000


### 3.2 事务回滚(扣款失败)
POST http://127.0.0.1:8190/api/v1/order/createOrder
Content-Type: application/x-www-form-urlencoded
X-GATEWAY-UID: 2

productId=1&number=2000
