xxl:
  job:
    admin:
      ### xxl-job admin address list, such as "http://address" or "http://address01,http://address02"
      addresses: http://localhost:8580/xxl-job-admin
    executor:
      ### xxl-job executor appname
      appname: shop-job-executor
      port: 9999
      logpath: ~/shop-cloud-logs/shop-job-executor
      logretentiondays: 30
