POST http://127.0.0.1:8590/api/v1/user/register
Content-Type: application/json

{
  "nickname": "zhou",
  "phone": "18511111111",
  "pwd": "test"
}

###
POST http://127.0.0.1:8590/api/v1/user/login
Content-Type: application/json

{
  "nickname": "zhou",
  "phone": "18511111111",
  "pwd": "test"
}

###
GET http://127.0.0.1:8590/api/v1/user/getUser
satoken: Bearer 5420ab10-6dbe-43e0-8181-8cecc8490888