# sa-token配置
sa-token:
  # SSO-相关配置
  sso-client:
    # SSO-Server 端主机地址
    server-url: http://sa-sso-server.com:8590

  # 配置Sa-Token单独使用的Redis连接 （此处需要和SSO-Server端连接同一个Redis）
  alone-redis:
    # Redis数据库索引 (默认为0)
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 16379
    # Redis服务器连接密码（默认为空）
    password: meetredis
    # 连接超时时间
    timeout: 10s
  is-print: false
  is-log: true
  sign:
    secret-key: kQwIOrYvnXmSDkwEiFngrKidMcdrgKor